using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using Conreign.Core.Utility;

namespace Conreign.Core.Editor
{
    public static class Sequences
    {
        private static readonly List<string> Nicknames = new List<string>
        {
            "Aspect",
            "Kraken",
            "Bender",
            "Lynch",
            "Big Papa",
            "Mad Dog",
            "Bowser",
            "O'Doyle",
            "Bruise",
            "Psycho",
            "Cannon",
            "Ranger",
            "Clink",
            "Ratchet",
            "Cobra",
            "Reaper",
            "Colt",
            "Rigs",
            "Crank",
            "Ripley",
            "Creep",
            "Roadkill",
            "Daemon",
            "Ronin",
            "Decay",
            "Rubble",
            "Diablo",
            "Sasquatch",
            "Doom",
            "Scar",
            "Dracula",
            "Shiver",
            "Dragon",
            "Skinner",
            "Fender",
            "Skull Crusher",
            "Fester",
            "Slasher",
            "Fisheye",
            "Steelshot",
            "Flack",
            "Surge",
            "Gargoyle",
            "Sythe",
            "Grave",
            "Trip",
            "Gunner",
            "Trooper",
            "Hash",
            "Tweek",
            "Hashtag",
            "Vein",
            "Indominus",
            "Void",
            "Ironclad",
            "Wardon",
            "Killer",
            "Wraith",
            "Knuckles",
            "Zero",
            "Steel",
            "Kevlar",
            "Lightning",
            "Tito",
            "Bullet-Proof",
            "Fire-Bred",
            "Titanium",
            "Hurricane",
            "Ironsides",
            "Iron-Cut",
            "Tempest",
            "Iron Heart",
            "Steel Forge",
            "Pursuit",
            "Steel Foil",
            "Upsurge",
            "Uprising",
            "Overthrow",
            "Breaker",
            "Sabotage",
            "Dissent",
            "Subversion",
            "Rebellion",
            "Insurgent",
            "Loch",
            "Golem",
            "Wendigo",
            "Rex",
            "Hydra",
            "Behemoth",
            "Balrog",
            "Manticore",
            "Gorgon",
            "Basilisk",
            "Minotaur",
            "Leviathan",
            "Cerberus",
            "Mothman",
            "Sylla",
            "Charybdis",
            "Orthros",
            "Baal",
            "Cyclops",
            "Satyr",
            "Azrael",
            "Ballistic",
            "Furor",
            "Uproar",
            "Fury",
            "Ire",
            "Demented",
            "Wrath",
            "Madness",
            "Schizo",
            "Rage",
            "Savage",
            "Manic",
            "Frenzy",
            "Mania",
            "Derange",
            "V",
            "Atilla",
            "Darko",
            "Terminator",
            "Conqueror",
            "Mad Max",
            "Siddhartha",
            "Suleiman",
            "Billy the Butcher",
            "Thor",
            "Napoleon",
            "Maximus",
            "Khan",
            "Geronimo",
            "Leon",
            "Leonidas",
            "Dutch",
            "Cyrus",
            "Hannibal",
            "Dux",
            "Mr. Blonde",
            "Agrippa",
            "Jesse James",
            "Matrix",
            "Bleed",
            "X-Skull",
            "Gut",
            "Nail",
            "Jawbone",
            "Socket",
            "Fist",
            "Skeleton",
            "Footslam",
            "Tooth",
            "Craniax",
            "Head-Knocker",
            "K-9",
            "Bone",
            "Razor",
            "Kneecap",
            "Cut",
            "Slaughter",
            "Soleus",
            "Gash",
            "Scalp",
            "Blood",
            "Scab",
            "Torque",
            "Wracker",
            "Annihilator",
            "Finisher",
            "Wrecker",
            "Destroyer",
            "Overtaker",
            "Clencher",
            "Stabber",
            "Saboteur",
            "Masher",
            "Hitter",
            "Rebel",
            "Crusher",
            "Obliterator",
            "Eliminator",
            "Slammer",
            "Exterminator",
            "Hell-Raiser",
            "Thrasher",
            "Ruiner",
            "Mutant",
            "Torpedo",
            "Wildcat",
            "Automatic",
            "Cannon",
            "Hellcat",
            "Glock",
            "Mortar",
            "Tomcat",
            "Sniper",
            "Siege",
            "Panther",
            "Carbine",
            "Bullet",
            "Jaguar",
            "Javelin",
            "Aero",
            "Bomber",
            "Howitzer",
            "Albatross",
            "Strike Eagle",
            "Gatling",
            "Arsenal",
            "Rimfire",
            "Avenger",
            "Hornet",
            "Centerfire",
            "Hazzard",
            "Demolition",
            "Power Train",
            "Yarder",
            "Chainsaw",
            "Excavator",
            "Trencher",
            "Wrench",
            "Shovel",
            "Pile Driver",
            "Terror",
            "Demise",
            "Phantom",
            "Freak",
            "Grim",
            "Sepulcher",
            "Axe",
            "Menace",
            "Damned",
            "Axe-man",
            "Dementor",
            "Kafka",
            "Executioner",
            "Nightshade",
            "Phantasm",
            "Hollowman",
            "Venom",
            "Scream",
            "Garrot",
            "The Unholy",
            "Shriek",
            "Abyss",
            "Rot",
            "Wraith",
            "Chasm",
            "Omen",
            "Bodybag",
            "Ghoul",
            "Midnight",
            "Morgue",
            "Mace",
            "Falchion",
            "Montante",
            "Battleaxe",
            "Zweihander",
            "Hatchet",
            "Billhook",
            "Club",
            "Hammer",
            "Caltrop",
            "Maul",
            "Sledgehammer",
            "Longbow",
            "Bludgeon",
            "Harpoon",
            "Crossbow",
            "Lance",
            "Angon",
            "Pike",
            "Tiger Claw",
            "Fire Lance",
            "Poleaxe",
            "Brass Knuckle",
            "Matchlock",
            "Quarterstaff",
            "Gauntlet",
            "Bullwhip",
            "War Hammer",
            "Katar",
            "Flying Claw",
            "Spear",
            "Dagger",
            "Slungshot",
            "Katana",
            "Gladius",
            "Aspis",
            "Saber",
            "Cutlass",
            "Blade",
            "Broadsword",
            "Scimitar",
            "Lockback",
            "Claymore",
            "Espada",
            "Machete",
            "Grizzly",
            "Wolverine",
            "Deathstalker",
            "Snake",
            "Wolf",
            "Scorpion",
            "Vulture",
            "Claw",
            "Boomslang",
            "Falcon",
            "Fang",
            "Viper",
            "Ram",
            "Grip",
            "Sting",
            "Boar",
            "Black Mamba",
            "Lash",
            "Tusk",
            "Goshawk",
            "Gnaw",
            "Amazon",
            "Majesty",
            "Anomoly",
            "Malice",
            "Banshee",
            "Mannequin",
            "Belladonna",
            "Minx",
            "Beretta",
            "Mirage",
            "Black Beauty",
            "Nightmare",
            "Calypso",
            "Nova",
            "Carbon",
            "Pumps",
            "Cascade",
            "Raven",
            "Colada",
            "Resin",
            "Cosma",
            "Riveter",
            "Cougar",
            "Rogue",
            "Countess",
            "Roulette",
            "Enchantress",
            "Shadow",
            "Enigma",
            "Siren",
            "Femme Fatale",
            "Stiletto",
            "Firecracker",
            "Tattoo",
            "Geisha",
            "T-Back",
            "Goddess",
            "Temperance",
            "Half Pint",
            "Tequila",
            "Harlem",
            "Terror",
            "Heroin",
            "Thunderbird",
            "Infinity",
            "Ultra",
            "Insomnia",
            "Vanity",
            "Ivy",
            "Velvet",
            "Legacy",
            "Vixen",
            "Lithium",
            "Voodoo",
            "Lolita",
            "Wicked",
            "Lotus",
            "Widow",
            "Mademoiselle",
            "Xenon",
            "Kahina",
            "Teuta",
            "Isis",
            "Dihya",
            "Artemis",
            "Nefertiti",
            "Running Eagle",
            "Atalanta",
            "Sekhmet",
            "Colestah",
            "Athena",
            "Ishtar",
            "Calamity Jane",
            "Enyo",
            "Ashtart",
            "Pearl Heart",
            "Bellona",
            "Juno",
            "Belle Starr",
            "White Tights",
            "Tanit",
            "Hua Mulan",
            "Shieldmaiden",
            "Devi",
            "Boudica",
            "Valkyrie",
            "Selkie",
            "Medb",
            "Cleo",
            "Venus",
            "Madam",
            "Empress",
            "Marquess",
            "Duchess",
            "Baroness",
            "Herzogin",
            "Fate",
            "Beguile",
            "Deviant",
            "Illusion",
            "Crafty",
            "Variance",
            "Delusion",
            "Deceit",
            "Caprice",
            "Deception",
            "Waylay",
            "Aberr",
            "Myth",
            "Ambush",
            "Variant",
            "Daydream",
            "Feint",
            "Hero",
            "Night Terror",
            "Catch-22",
            "Villain",
            "Figment",
            "Puzzler",
            "Daredevil",
            "Virtual",
            "Curio",
            "Mercenary",
            "Chicanery",
            "Prodigy",
            "Voyager",
            "Trick",
            "Breach",
            "Wanderer",
            "Vile",
            "Miss Fortune",
            "Audacity",
            "Horror",
            "Vex",
            "Swagger",
            "Dismay",
            "Grudge",
            "Nerve",
            "Phobia",
            "Enmity",
            "Egomania",
            "Fright",
            "Animus",
            "Scheme",
            "Panic",
            "Hostility",
            "Paramour",
            "Agony",
            "Rancor",
            "X-hibit",
            "Inferno",
            "Malevolence",
            "Charade",
            "Blaze",
            "Poison",
            "Hauteur",
            "Crucible",
            "Spite",
            "Vainglory",
            "Haunter",
            "Spitefulness",
            "Narcissus",
            "Bane",
            "Venom",
            "Brass",
            "Camden",
            "Baltimore",
            "Crown Heights",
            "Detroit",
            "L.A.",
            "Dirty Dirty",
            "McKinley",
            "NYC",
            "ATL",
            "Fiend",
            "Spirit",
            "Spellbinder",
            "Goblin",
            "Kelpie",
            "Jezebel",
            "Oracle",
            "Vamp",
            "Sorceress",
            "Soul",
            "Temptress",
            "She-Devil",
            "Revenant",
            "Diviner",
            "Hellcat",
            "Poltergeist",
            "Exorcist",
            "She-Wolf",
            "Zombie",
            "Seer",
            "Madcap",
            "Armor",
            "Blaser",
            "Savage",
            "Benelli",
            "Glock",
            "Seraphim",
            "Remington",
            "Ruger",
            "Winchester",
            "Aeon",
            "Tank",
            "Hawkeye",
            "Kiddo",
            "Torchy",
            "Medusa",
            "Buffy",
            "Trinity",
            "Irons",
            "Coffy",
            "Zoe",
            "Storm",
            "Eowyn",
            "Zen",
            "Jubilee",
            "Croft",
            "Alyx",
            "Dazzler",
            "Leeloo",
            "Katniss",
            "Aeryn",
            "Mathilda",
            "Linh",
            "Arya",
            "Padme",
            "Polgara",
            "Ygritte",
            "Ramona",
            "Elektra",
            "Bayonetta",
            "Silk Spectre",
            "Catwoman",
            "Sindel",
            "Helium",
            "Mercury",
            "Entropy",
            "Beryllium",
            "Radon",
            "Radioactive",
            "Neon",
            "Radium",
            "Radiate",
            "Phosphorus",
            "Element",
            "Ion",
            "Phosphorescent",
            "Elemental",
            "Eon",
            "Illumine",
            "Lab Rat",
            "Photon",
            "Chromium",
            "Acid",
            "Redox",
            "Arsenic",
            "Atom",
            "Redux",
            "Zinc",
            "Electron",
            "Hot Salt",
            "Selenium",
            "Atomic",
            "Vapor",
            "Xenon",
            "Nuclear",
            "Volt",
            "Osmium",
            "Earth Metal",
            "X-Ray",
            "Fox",
            "Nightshade",
            "Immortal",
            "Coyote",
            "Mercury",
            "Meteor",
            "Crow",
            "Cyanide",
            "Comet",
            "Spider",
            "Toxin",
            "Protostar",
            "Bat",
            "Virus",
            "Medium",
            "Serpent",
            "Arsenic",
            "Dark Matter",
            "Satyr",
            "Orb",
            "Hypernova",
            "Oleander",
            "Astor",
            "Stratosphere",
            "Hemlock",
            "Mortal",
            "Supernova",
            "Vegas",
            "Snake Eyes",
            "Militant",
            "Blackjack",
            "High Roller",
            "Lock",
            "Baccarat",
            "Pocket Rocket",
            "The Money",
            "Red Dog",
            "Mojave",
            "Dice",
            "Poker",
            "Bellagio",
            "Rocks",
            "Keno",
            "Nevada",
            "Watchface",
            "The House",
            "Reno",
            "Big Time",
            "Bookie",
            "Steppe",
            "Two Face",
            "Arbitrage",
            "Fishnet",
            "Deep Pockets",
            "Double Double",
            "Dagger",
            "Real Deal",
            "Explosive",
            "Grenade",
            "Pyro",
            "Black Cat",
            "Roman Candle",
            "Gunpowder",
            "M-80",
            "Babylon Candle",
            "Mortar",
            "Smoke Bomb",
            "Missile",
            "Firebringer",
            "Amaretto",
            "Dom",
            "Noir",
            "Bacardi",
            "Don",
            "Scotch",
            "Cognac",
            "Joose",
            "Whiskey",
            "Forever",
            "Revolution",
            "Berserk",
            "Unstoppable",
            "Sever",
            "Bitten",
            "Eternity",
            "Die-hard",
            "Corybantic",
            "Fanatic",
            "Zealot",
            "Crazed",
            "X-Treme",
            "Alien",
            "Delirious",
            "Rabid",
            "Predator",
            "Agitator",
            "Radical",
            "Barbarian",
            "Maniac"
        };

        private static readonly HashSet<int> PopularColors = new HashSet<int>
        {
            0xff0000,
            0x008080,
            0xffe4e1,
            0x0000ff,
            0xd3ffce,
            0x40e0d0,
            0xffd700,
            0xff7373,
            0xb0e0e6,
            0xcccccc,
            0x666666,
            0xf6546a,
            0x333333,
            0x003366,
            0xffa500,
            0x800080,
            0x66cdaa,
            0x800000,
            0x008000,
            0xf08080,
            0xcc0000
        };

        public static IEnumerable<string> RandomWithPopularFirstColors
        {
            get
            {
                foreach (var color in PopularColors.Shuffle())
                {
                    yield return $"#{color:x6}";
                }

                var random = new Random();
                var used = new HashSet<int>(PopularColors);
                while (used.Count < 0xffffff + 1)
                {
                    int next;
                    do
                    {
                        next = random.Next(minValue: 0, maxValue: 0xffffff + 1);
                    } while (used.Contains(next));

                    used.Add(next);
                    yield return $"#{next:x6}";
                }
            }
        }

        public static IEnumerable<string> Colors =>
            Enumerable.Range(start: 0, count: 0xffffff + 1).Select(x => $"#{x:x6}");

        public static IEnumerable<string> PlanetNames
        {
            get
            {
                var buffer = new List<string> {""};
                while (true)
                {
                    var output = new List<string>();
                    foreach (var item in buffer)
                    foreach (var letter in Alphabet)
                    {
                        var name = string.Concat(item, letter);
                        output.Add(name);
                        yield return name;
                    }

                    buffer = output;
                }

                // ReSharper disable once IteratorNeverReturns
            }
        }

        private static IEnumerable<string> Alphabet
        {
            get
            {
                var c = 'A';
                while (c < 'Z')
                {
                    yield return c.ToString();
                    c++;
                }
            }
        }

        public static IEnumerable<string> RandomNicknames => Nicknames
            .Shuffle()
            .Select(x => x.ToLower(CultureInfo.InvariantCulture));
    }
}